services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: personapi-dotnet
    ports:
      - "9090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-db;Database=persona_db;User Id=sa;Password=SaPassw0rd!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      - SA_PASSWORD=SaPassw0rd!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mssql_data:
